@echo off
REM Auto-generated by CMake - DO NOT EDIT MANUALLY
REM This script allows building without CMake installed
REM Auto-detects compiler: MSVC, Clang, MinGW GCC

setlocal enabledelayedexpansion
cd /d "%~dp0\libvscode-diff"

REM Create build directory
if not exist build mkdir build

echo Building vscode_diff (standalone mode)...
echo Platform: Windows

REM Source files (including bundled utf8proc)
set SOURCES=^
src\diff_api.c ^
src\render_plan.c ^
default_lines_diff_computer.c ^
src\char_level.c ^
src\line_level.c ^
src\myers.c ^
src\optimize.c ^
src\sequence.c ^
src\range_mapping.c ^
src\string_hash_map.c ^
src\utils.c ^
src\print_utils.c ^
src\utf8_utils.c ^
vendor\utf8proc.c

REM Auto-detect compiler
set COMPILER=unknown

where cl.exe >nul 2>&1
if !errorlevel! == 0 (
    set COMPILER=msvc
    goto :build_msvc
)

where clang.exe >nul 2>&1
if !errorlevel! == 0 (
    set COMPILER=clang
    goto :build_clang
)

where gcc.exe >nul 2>&1
if !errorlevel! == 0 (
    set COMPILER=gcc
    goto :build_gcc
)

echo Error: No C compiler found!
echo Please install one of: Visual Studio (MSVC), Clang, MinGW-w64
cd ..
exit /b 1

:build_msvc
echo Using MSVC compiler...
cl.exe /LD /O2 /W3 /std:c11 /DUTF8PROC_STATIC /Iinclude /Ivendor /Fobuild\ /Fdbuild\ /Fe:build\libvscode_diff.dll %SOURCES% /link /DLL
goto :build_done

:build_clang
echo Using Clang compiler...
if not exist build mkdir build
clang.exe -shared -Wall -Wextra -std=c11 -O2 -Iinclude -Ivendor -o build\libvscode_diff.dll %SOURCES%
goto :build_done

:build_gcc
echo Using MinGW GCC compiler...
if not exist build mkdir build
gcc.exe -shared -Wall -Wextra -std=c11 -O2 -Iinclude -Ivendor -o build\libvscode_diff.dll %SOURCES%
goto :build_done

:build_done
if !errorlevel! neq 0 (
    echo Build failed!
    cd ..
    exit /b 1
)

echo Installing to plugin root...
copy /Y build\libvscode_diff.dll ..\libvscode_diff.dll >nul

echo.
echo ✓ Build successful: libvscode_diff.dll
echo   Build artifacts in: libvscode-diff\build\
cd ..
endlocal
