name: 'Setup Neovim'
description: 'Install Neovim nightly on Ubuntu, macOS, or Windows'
inputs:
  arch:
    description: 'Architecture (x64 or arm64)'
    required: false
    default: 'x64'
runs:
  using: 'composite'
  steps:
    - name: Install Neovim (Ubuntu)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        ARCH="linux-x86_64"
        if [ "${{ inputs.arch }}" = "arm64" ]; then
          ARCH="linux-arm64"
        fi
        curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-$ARCH.tar.gz
        tar xzf nvim-$ARCH.tar.gz
        sudo cp -r nvim-$ARCH/* /usr/local/
        nvim --version | head -n 1

    - name: Install Neovim (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        ARCH="macos-arm64"
        if [ "${{ inputs.arch }}" = "x64" ]; then
          ARCH="macos-x86_64"
        fi
        curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-$ARCH.tar.gz
        tar xzf nvim-$ARCH.tar.gz
        sudo cp -r nvim-$ARCH/* /usr/local/
        nvim --version | head -n 1

    - name: Install Neovim (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $arch = "${{ inputs.arch }}"
        $archSuffix = if ($arch -eq "arm64") { "-arm64" } else { "64" }
        $downloadUrl = "https://github.com/neovim/neovim/releases/download/nightly/nvim-win$archSuffix.zip"
        $installPath = "C:\tools\neovim"
        
        Write-Host "Downloading Neovim from $downloadUrl"
        Invoke-WebRequest -Uri $downloadUrl -OutFile "$env:TEMP\nvim.zip"
        
        New-Item -ItemType Directory -Force -Path $installPath | Out-Null
        Expand-Archive -Path "$env:TEMP\nvim.zip" -DestinationPath $installPath -Force
        
        $nvimBinPath = "$installPath\nvim-win$archSuffix\bin"
        echo "$nvimBinPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
        & "$nvimBinPath\nvim.exe" --version | Select-Object -First 1
